name: "Output HTML report to GitHub Check Runs"
description: "Output HTML report to GitHub Check Runs"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true

  report_path:
    description: "File path of a generated HTML report"
    required: true

  summary_selector:
    description: "CSS selector of HTML node to be shown as summary"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
