name: "units-test"

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: node_modules Cache
        uses: actions/cache@v1
        env:
          cache-name: node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./yarn.lock') }}

      - name: Install Yarn dependencies
        working-directory: ./
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test
        working-directory: ./
        continue-on-error: true
        run: |
          yarn test
